#PATHS
VEXRISCV_DIR ?= $(shell pwd)
VEXRISCV_SRC_DIR=$(VEXRISCV_DIR)/hardware/src
VEX_PLATAFORM_DIR=$(VEXRISCV_DIR)/software/opensbi_platform
VEX_CORE_DIR=$(VEXRISCV_DIR)/software/vexriscv_core
VEX_OS_DIR=$(VEXRISCV_DIR)/software/OS_build
VEX_OPENSBI_DIR=$(VEXRISCV_DIR)/submodules/OpenSBI

#RISC-V HARD MULTIPLIER AND DIVIDER INSTRUCTIONS
USE_MUL_DIV ?=1

#RISC-V ATOMIC INSTRUCTIONS
USE_ATOMIC ?=1

#RISC-V COMPRESSED INSTRUCTIONS
USE_COMPRESSED ?=1

#IOb-SoC L1 Cache
USE_L1_CACHE ?=0
