#!/bin/sh
echo "### INIT SCRIPT ###"
/bin/mkdir /proc /sys /tmp
/bin/mount -t proc none /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t tmpfs none /tmp

cat <<'EOF'
XXx     lOXWMMWXOl    :XK                                          XXo  XX.              
MMO   oWM.      ,MWo  cMN                                          MMd  MM.              
MMO  OMM          MMo cMMkKXXKk;   OO;    ,OO  ,OOoOKXKk:   ,x0XXKOMMd  MM.   lOKXKOo.   
MMO  MMo          oMM cMMk    XMK  MMl    :MM  cMMo   .MM, OMW    dMMd  MM. .WM.    MM;  
MMO  MMd          oMM cMM      MM: MMl    :MM  cMM     MM;'MM.     MMd  MM. WMN;,,''KMW  
MMO  OMW          WMo cMM      MM: MMl    lMM  cMM     MM;,MM.     MMd  MM. MMo          
MMO   lMN:      cWMl  cMMo    kMM  MM0    NMM  cMM     MM; WM0    oMMd  MM. :MX.   .OK,  
MMO     ;MMX00XMM'    cMMMNO0WM,   .MMKkOWWMM  cMM     MM;  ,MW0OXMMMd  MM.   MMKO0MM    
EOF
echo 'OpenCryptoLinux >   '
echo -e "\nThis boot took $(cut -d' ' -f1 /proc/uptime) seconds\n"
/bin/sh +m
